### PR TITLE
Send Dalamud user-agent when downloading plugins

### PR DESCRIPTION
**Pull request by lojewalo**
The sequel to https://github.com/goatcorp/Dalamud/pull/1486.

### CODE REVIEW

**Review by KazWolfe — APPROVED** [review]
Nice, you got to the thing I was going to mention before I even had to say it.

**Review by goaaats — CHANGES_REQUESTED** [review]
This is now the same as https://github.com/goatcorp/Dalamud/blob/master/Dalamud/Plugin/Internal/Types/PluginRepository.cs#L50, is that one still required? Can you remove it if it's not?

**Comment by lojewalo** [comment]
No, they're separate `HttpClient` instances.

**Comment by KazWolfe** [comment]
> This is now the same as https://github.com/goatcorp/Dalamud/blob/master/Dalamud/Plugin/Internal/Types/PluginRepository.cs#L50, is that one still required? Can you remove it if it's not?

Yeah, it is because we need to set additional default settings there (specifically `Timeout`) that we don't necessarily want on our global shared HTTP client. We can rewrite that class to use the global client and specify our timeouts via cancellation tokens if we really wanted to, I suppose.

**Comment by goaaats** [comment]
That probably should have been the approach then, it's better to use one client per application in either case. I don't think it should be hardcoded in two separate spots.

**Pull request merged**
