### PR TITLE
[master] Update ClientStructs

### PR DESCRIPTION
**Pull request by bleatbot**

### CODE REVIEW

**Comment by wolfcomp** [comment]
Do not merge until the next action run, as there was a slight-unseen issue when I checked one of the PRs for CS and didn't catch that some of the types were wrong. This was fixed with aers/FFXIVClientStructs#724

**Comment by wolfcomp** [comment]
Might be nice to consider merging this after aers/FFXIVClientStructs#701 is merged as it will include a lot of new systems possibly desired by a few main repo plugins.

**Comment by KazWolfe** [comment]
`AddonActionBarCross` was completely deleted. While it appears to be renamed to `AddonActionCross`, this *is* a breaking change to the CS API.

**Comment by wolfcomp** [comment]
Only the filename was changed to match the class name.
The namespace is the exact same as is the class name.

**Review by KazWolfe — APPROVED** [review]

**Pull request merged**
