### PR TITLE
Added GetWindows() function

### PR DESCRIPTION
**Pull request by LadyDefile**
# Dalamad.Interface.Windowing.WindowSystem.cs
* Added GetWindows() function to return the window collection as an array. Returning as array not List<Window> to protect encapsulation.

### CODE REVIEW

**Comment by goaaats** [comment]
In a more idiomatic way, foregoing the array conversion, you can write this as:

```cs
public IReadOnlyList Windows => this.windows;
```

**Comment by LadyDefile** [comment]
@goaaats I changed it to use IReadOnlyList.

**Comment by goaaats** [comment]
You should make it a property actually - makes more sense here as the function doesn't actually do anything and we don't usually do getter functions like that. Sorry, should have been more clear.

**Comment by LadyDefile** [comment]
@goaaats Done. Sorry to make you work so hard. LOL

**Review by goaaats — APPROVED** [review]

**Pull request merged**
