### PR TITLE
Add InventoryWidget

### PR DESCRIPTION
**Pull request by Haselnussbomber**
I thought it may be useful to have a widget showing Inventory containers and their items.

Screenshot1

Collectables:
Screenshot2

High Quality:
Screenshot3

### CODE REVIEW

**Comment by Haselnussbomber** [comment]
Updated to use `GameInventoryItem.GetReadOnlySpanOfInventory`.
Also now displays Stains and Materia if the item supports them.

Screenshot

**Review by KazWolfe — APPROVED** [review]
Approved if only I want a reason to check item IDs without Simple Tweaks.

**Comment by Haselnussbomber** [comment]
It's not about you, it's about bringing popular debug features from a plugin into Dalamud, because said plugin might be down when we want to fix CS and Dalamud. But thanks for approving.

**Comment by KazWolfe** [comment]
That was indeed the point.

**Pull request merged**
