### PR TITLE
Implement market board purchase message reading

### PR DESCRIPTION
**Pull request by karashiiro**
It's only been five months, I'm not too late on this.

I'll finish this PR over the next few days (opening it so I remember to).

### The stuff
 * [x] Add parsers for purchase network events
 * [x] Add complete upload process for the listing delete endpoint
 * [x] Add opcodes for the relevant network events
 * [x] [Implement functionality in Universalis](https://github.com/Universalis-FFXIV/Universalis/issues/433)

### CODE REVIEW

**Comment by karashiiro** [comment]
Opcode scanners were added in https://github.com/karashiiro/FFXIVOpcodes/pull/19 - I'll need to PR DalamudAssets as well to add these (note to self).

**Comment by karashiiro** [comment]
Err, update them, not add them.

**Comment by karashiiro** [comment]
Nevermind, looks like that’s been getting done.

**Comment by Aireil** [comment]
The client opcode file wasn't updated, so just need to update MarketBoardPurchaseHandler.

**Comment by karashiiro** [comment]
PR'd in https://github.com/goatcorp/DalamudAssets/pull/17

**Comment by goaaats** [comment]
Let me know when this is ready.

**Comment by karashiiro** [comment]
Added PR checklist

**Comment by karashiiro** [comment]
As I'm wrapping this up today, should I open a separate PR for the api3 branch to get this in before 6.0? I'm seeing that it has no new commits over master.

**Comment by goaaats** [comment]
I don't think I will make another release of api3 if nothing breaks until November, but feel free, if it's not too much work to rebase.

**Comment by karashiiro** [comment]
I’ll probably just create new commits for that, then, since I’ve already replayed all of the .NET 5 commits on this branch (or cherry-pick, maybe).

**Comment by karashiiro** [comment]
Ready to merge (finally) 🥴

**Comment by daemitus** [comment]
Now just wait for me to clobber the shit out of it from a bunch of my other pending PRs :)

**Comment by karashiiro** [comment]
😔

**Review by goaaats — APPROVED** [review]

**Pull request merged**
