### PR TITLE
Fix SeString serialization/deserialization

### LINKED ISSUE #779: SeStrings can't be serialized
Trying to serialize SeString, either with saving plugin config or directly through JsonConvert results in this error:
```
2022-03-20 22:40:48.183 +03:00 [ERR] [TestPlugin] Unable to serialize instance of 'System.IO.DirectoryInfo'.
   at Newtonsoft.Json.Serialization.DefaultContractResolver.ThrowUnableToSerializeError(Object o, StreamingContext context)
   at Newtonsoft.Json.Serialization.JsonContract.InvokeOnSerializing(Object o, StreamingContext context)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.OnSerializing(JsonWriter writer, JsonContract contract, Object value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at Dalamud.Configuration.PluginConfigurations.Save(IPluginConfiguration config, String pluginName) in C:\goatsoft\companysecrets\dalamud\Configuration\PluginConfigurations.cs:line 35
   at Dalamud.Plugin.DalamudPluginInterface.SavePluginConfig(IPluginConfiguration currentConfig) in C:\goatsoft\companysecrets\dalamud\Plugin\DalamudPluginInterface.cs:line 271
   at TestPlugin.TestPlugin..ctor(DalamudPluginInterface pluginInterface) in C:\VS\TestPlugin\TestPlugin\TestPlugin.cs:line 38
```
Example code:
```
using Dalamud.Logging;
using Dalamud.Plugin;
using System;
using Dalamud.Game.Text.SeStringHandling;
using Dalamud.Configuration;

namespace TestPlugin
{
    unsafe public class TestPlugin : IDalamudPlugin
    {
        public string Name => "TestPlugin";
        Config config;

        public TestPlugin(DalamudPluginInterface pluginInterface)
        {
            try
            {
                config = pluginInterface.GetPluginConfig() as Config ?? new();
                config.sestring = new SeStringBuilder().AddText("Some text").Build();
                pluginInterface.SavePluginConfig(config);
            }
            catch(Exception e)
            {
                PluginLog.Error($"{e.Message}\n{e.StackTrace ?? ""}");
            }
        }
        
        class Config : IPluginConfiguration
        {
            public int Version { get; set; } = 1;
            public SeString sestring = new();
        }

        public void Dispose()
        {

        }

    }
}
```

### PR DESCRIPTION
**Pull request by karashiiro**
Fixes #779

### CODE REVIEW

**Comment by karashiiro** [comment]
Oh, I forgot to use the new deserialize method in Load, I'll fix that when I get home.

**Comment by karashiiro** [comment]
Fixed, this is ready to be reviewed.

**Review by goaaats — APPROVED** [review]

**Comment by Aireil** [comment]
This was pushed on master, not on net5, was it intended?

**Comment by karashiiro** [comment]
Oh, I wasn't aware that master was targeting .NET 6, my bad.

**Comment by karashiiro** [comment]
What should we do about this? I can cherry-pick it and PR it to net5, but that might cause issues if we merge net5 changes into master later.

**Pull request merged**
