### PR TITLE
Add PluginScoped Nags

### PR DESCRIPTION
**Pull request by MidoriKami**

### CODE REVIEW

**Comment by MidoriKami** [comment]
Didn't notice GameInventoryTestWidget required instances of a GameInventoryPluginScoped, as it was the last service nag I added, assumed it would just work.

The GameInventoryTestWidget shouldn't be using scoped instances to test core functionality.

**Comment by MidoriKami** [comment]
Removed GameInventory Nags for now.

**Comment by KazWolfe** [comment]
Rather than doing this on a per-service scope, would it be possible to do this at the service manager level if a specific `NeedsCleanup` var is present? Would be cleaner and have less code everywhere, I'd think.

**Comment by MidoriKami** [comment]
stale closing

**Pull request closed without merging**
