### PR TITLE
Replace EasyHook hooking with Reloaded

### PR DESCRIPTION
**Pull request by goaaats**
this is a direct port of Adam's changes

### CODE REVIEW

**Comment by NotAdam** [comment]
fyi this will break all hooks because the package on nuget doesn't include the default calling convention for x64 hooks

**Comment by goaaats** [comment]
Ah oops, haven't tested myself yet cause I can't play the game atm, was waiting for Cara to test - will probably put this on hold then since only penumbra needs it? Or would you rather we submodule it for now?

**Comment by NotAdam** [comment]
the problem with using a submodule is that it breaks because of the discord.net stuff using old versions of system.compilerservices.unsafe, and when I last looked, that was a huge pita to update because it was a few dependencies deep

**Comment by goaaats** [comment]
Works like this now, with all deps having System.Runtime.CompilerServices.Unsafe v4.5.2

**Comment by daemitus** [comment]
Mission accomplished.

**Pull request closed without merging**
