### PR TITLE
Add "GetUiObjectByName"

### PR DESCRIPTION
**Pull request by Caraxi**

### CODE REVIEW

**Comment by goaaats** [comment]
I'm not sure if I want to merge this without having more infrastructure around it, like structs and an array to list open windows - will think about it, and maybe add myself

**Comment by Caraxi** [comment]
That’s fine. Just trying to avoid having 8 plugins scanning for the same 2 functions lol

**Comment by goaaats** [comment]
For sure, do you have the object mapped out somewhere?
We'll probably be redesigning this for "Dalamud 2: It's not shit anymore" anyways so I might as well go for it.

**Comment by Caraxi** [comment]
Only the basic structure I've needed. Others probably have a more fleshed out structure

**Review by goaaats — APPROVED** [review]

**Pull request merged**
