### PR TITLE
ISIT: remove api9 compat, IDAM: make Empty4X4 transparent

### PR DESCRIPTION
**Pull request by Soreepeong**

### CODE REVIEW

**Comment by goaaats** [comment]
What are the consequences of merging this now? Have we removed all of the ways to access this legacy stuff?

**Comment by Soreepeong** [comment]
The functions removed are used only for supporting API9 texture provider functions. It should be safe to remove them.

**Comment by goaaats** [comment]
Perfect, thank you.

**Comment by Soreepeong** [comment]
Since #1879 exists, ISIT support to INM is removed from this PR; instead, fixed Empty4X4 to be actually transparent.

**Review by goaaats — APPROVED** [review]

**Pull request merged**
