### PR TITLE
feat: add new 7.0 BitmapFontIcons & fix few others

### PR DESCRIPTION
**Pull request by Pilzinsel64**
### Added

- Tuiyolal flag
- Viper job icon
- Pictomancer job icon
- Venture Delivery Moogle

grafik

### Fixed

- BlueStarProblem _(new id is 122)_
- Alchemist _(new id is 141, copy&paste issue?)_
- Culinarian _(new id is 142, copy&paste issue?)_

### CODE REVIEW

**Comment by Caraxi** [comment]
`MoogleTreasureTrove` is actually more likely `VentureDeliveryMoogle`

image
image
image

**Comment by Pilzinsel64** [comment]
Updated! Thanks. Had no idea what it is. 😄

**Comment by PunishedPineapple** [comment]
@Pilzinsel64 Idk if you want to add it with these or not, but icon 123 is the PlayStation Plus icon.  It will display as blank if the PS3/PS4/PS5 textures are not being used, though.  Additionally, you might want to call 169 Tural instead of Tuliyollal, since it's used for the entire region (minus Alexandrian the areas), not just the city.

Sorry to butt in; I was going to try to update these, and then saw your PR.

**Comment by Pilzinsel64** [comment]
@PunishedPineapple Thanks for the hint! Added it just now.

**Comment by Pilzinsel64** [comment]
Sorry for the dirty history btw. Can clean it up if you want. Either tell me or just squash on merge.

**Comment by Caraxi** [comment]
> Sorry for the dirty commit history btw. Can clean it up if you want. Either tell me or just squash on merge.

Its always squash merge here

**Review by goaaats — APPROVED** [review]

**Pull request merged**
