### PR TITLE
[master] Update ClientStructs

### PR DESCRIPTION
**Pull request by bleatbot**

### CODE REVIEW

**Comment by KazWolfe** [comment]
n.b. Minor breaking changes in `HousingWorkshopTerritory.cs`. Unknown fields were renamed with proper values.

**Review by KazWolfe — DISMISSED** [review]
Approved pending a secondary sign-off that we're ok with these breaking changes.

**Comment by Caraxi** [comment]
> n.b. Minor breaking changes in `HousingWorkshopTerritory.cs`. Unknown fields were renamed with proper values.

https://github.com/aers/FFXIVClientStructs/commit/e61e4d8fa9e58e37b454314f0f9a9f305f173483
Unbroke

**Comment by wolfcomp** [comment]
The breaking changes wouldn't have affected any first party plugin, as SubmarineTracker uses their own structs until the new one would be merged in.

**Pull request merged**
