### PR TITLE
wip actor improvements

### PR DESCRIPTION
**Pull request by NotAdam**
things to do:

- [x] remove all the old actor cache garbage
- [x] why is everything an int when it should be uint?

### CODE REVIEW

**Comment by Caraxi** [comment]
... I edited it by accident but 
>  why is everything an int when it should be uint?

is because fixing it is breaking

**Comment by NotAdam** [comment]
should just break it then because it's not correct, `DataId` is also wrong, should be named what it actually is instead of something generic

**Comment by goaaats** [comment]
We should check game state in ActorTable and remark that you should never store these for more than an update tick, if we're gonna end up going for unsafe, I guess

**Comment by NotAdam** [comment]
yeah i have some incredible patent pending™ technology to deal with this in an easy way

**Comment by goaaats** [comment]
We ported all of this pretty much, thanks for your work

**Pull request closed without merging**
