### PR TITLE
feat: validate player name

### PR DESCRIPTION
**Pull request by kalilistic**
**Test Cases (Input => Result)**
```
Rycharde Leatherby => True
Leatherby Goodfellow => True
Lodewicus Barlow => True
Hi Hi => True
J Smith => False
John S => False
Johnnnnnnnnnnn Sm => True
John Smithhhhhhhhhhhh => False
Johnnnnnnnnnnn Smithhhhhhh => False
Ke$ha Smith => False
Joh``n Smith => False
-John Smith => False
John `Smith => False
Jo`-hn Smith => False
Jo-`hn Smith => False
```

### CODE REVIEW

**Comment by karashiiro** [comment]
This will probably need to be patched over in the CN fork - I think CN has slightly different restrictions.

**Comment by kalilistic** [comment]
> This will probably need to be patched over in the CN fork - I think CN has slightly different restrictions.

Anything I can change to make that easier?

**Comment by karashiiro** [comment]
@Bluefissure

**Comment by Bluefissure** [comment]
There's no last name in CN character names, you can go ahead and we will patch it in our fork.

Thanks for letting me know btw. :)

**Comment by Loskh** [comment]
I found the function used in the game to validate player names, and tested it in both CN client and Global client. It works fine.
I think using this function can improve non-global client compatibility.
Code is here: https://gist.github.com/Loskh/c0c075d1494c9b1c63402e4bf5d06485

**Comment by kalilistic** [comment]
Very nice. I think this would require a CS update? I'd suggest I can close this PR and you can submit the function instead.

**Comment by kalilistic** [comment]
Maybe still worth merging? Someone could enhance this in the future using a func without breaking the API.

**Review by goaaats — APPROVED** [review]

**Pull request merged**
