### PR TITLE
Expose Dalamud's StartInfo in DalamudPluginInterface

### PR DESCRIPTION
**Pull request by rreminy**
Expose the Dalamud's StartInfo structure which contains the following information such as Game Version, Working Directory among other things.

May need more work to make sure the StartInfo fields are exposed securely, preferably converting them to properties

### CODE REVIEW

**Comment by NotAdam** [comment]
this is already covered by #450 fwiw

**Comment by rreminy** [comment]
Seems like a work in progress, I can't find where is StartInfo exposed in your code for plugins but will keep an eye.

**Comment by daemitus** [comment]
@rreminy If all goes to plan, the plugin Initialize method will become a constructor, where you can define the startInfo as one of the parameters to be passed in.

**Comment by rreminy** [comment]
Alright that can work, DI style then

**Comment by goaaats** [comment]
Thanks, we'll do this our way for API 4

**Pull request closed without merging**
