### PR TITLE
.NET 5.0 (ITS HAPPENING!)

### PR DESCRIPTION
**Pull request by daemitus**

### CODE REVIEW

**Comment by daemitus** [comment]
Currently when using Reloaded.Hooks, hooking D3D11.Present will cause a crash when calling the original hook.

Below is the delegate as defined by Reloaded's author in their own ImGui implementation. See https://github.com/Sewer56/Reloaded.Imgui.Hook/blob/master/Reloaded.Imgui.Hook/DirectX/Hooks/DX11Hook.cs#L70.
```
[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
[Reloaded.Hooks.Definitions.X64.Function(Reloaded.Hooks.Definitions.X64.CallingConventions.Microsoft)]
[Reloaded.Hooks.Definitions.X86.Function(Reloaded.Hooks.Definitions.X86.CallingConventions.Stdcall)]
private delegate IntPtr PresentDelegate(IntPtr swapChain, uint syncInterval, uint presentFlags);
```

When swapping out for CoreHook, it works exactly as intended. ImGui renders, plugins load, just works. So we know the signature works, and that the old previous delegate was correct. 

The question is then, why does Reloaded cause a crash?

**Comment by daemitus** [comment]
For anyone paying attention here, apparently reloaded is causing crashes due to the Discord overlay hooking the same function. Quitting discord and Dalamud boots up fine.

**Comment by goaaats** [comment]
I'd like to merge this very soon - please signal when you're ready and I'll go ahead resolving conflicts 👍

**Comment by daemitus** [comment]
You really dont want to resolve conflicts, since I moved a bunch of shit into internal namespaces. just take a minute though.

**Comment by daemitus** [comment]
@goaaats DO IT.

**Review by goaaats — APPROVED** [review]

**Comment by Caraxi** [comment]
broke DownloadLinkUpdate, need to revert

**Pull request merged**
