### PR TITLE
feat: add an option to disable RMT Filtering

### PR DESCRIPTION
**Pull request by Caraxi**

### CODE REVIEW

**Comment by goaaats** [comment]
Why? Are there false positives?

**Comment by Caraxi** [comment]
Occasionally

**Comment by Caraxi** [comment]
any time anyone talks about merch with bonus codes it false positives.

**Comment by goaaats** [comment]
Think we should consider either removing it altogether or improving the regex, even though I think there's still some value in having a basic filter built-in

**Comment by Caraxi** [comment]
improved or left how it is, it should still have an option to disable it if it doesn't get removed.

**Review by daemitus — APPROVED** [review]
Looks solid

**Pull request merged**
