### PR TITLE
File scoped namespaces, light cpp formatting

### PR DESCRIPTION
**Pull request by daemitus**
- File scoped namespaces for the injector
- Light auto-formatting of the cpp files.

Honestly, if you're trying to make sense of the CS file diffs, it'll probably be easier to do it yourself.

### CODE REVIEW

**Comment by goaaats** [comment]
It's fine for the injector, I'll do Dalamud itself - think there also was some blocker for that but I don't really remember, will have a go at it soon

**Comment by daemitus** [comment]
Got more in the pipeline, trying to keep changes manageable for reviewing.

**Comment by daemitus** [comment]
freshly applied on the net5 branch.

**Comment by KazWolfe** [comment]
Targeting net5 branch, I think it's safe to say this PR has gone stale. Sorry!

**Pull request closed without merging**
