### PR TITLE
IFontAtlas API9 compat: support reading GameFontHandle.ImFont during UiBuilder.After/BuildFonts

### PR DESCRIPTION
**Pull request by Soreepeong**
Also added `[Api10ToDo]` internal marker attribute.

### CODE REVIEW

**Comment by goaaats** [comment]
Could you also note the "migration step" plugins need to make to adapt to the new behavior, which we can put in patch notes? E.g. what code changes are necessary.

**Comment by Soreepeong** [comment]
Will do, but would do that in an another PR, as this PR intends to fix a crashing bug.

**Comment by goaaats** [comment]
I'll hold you to it

**Review by goaaats — APPROVED** [review]

**Comment by Soreepeong** [comment]
Also can you make it ignore the check API compatibility one? I've changed `IFontHandle.Push` to return a `struct FontPopper` instead of `IDisposable`, to reduce heap allocation per every frame.

**Comment by goaaats** [comment]
Yeah, all good. It's just "informational" for review, it won't block the submit. Thanks!

**Pull request merged**
